export const JRPG = [
    {
        id: 201,
        cat:'JRPG',
        name: 'Final Fantasy VII Remake',
        videoid:'ERgrFVhL-n4',
        imgUrl:'/images/JRPG/Final Fantasy VII Remake.jpg',
        dec:"Final Fantasy VII Remake[b] is a 2020 action role-playing game by Square Enix. It is the first in a planned trilogy of games remaking the 1997 PlayStation game Final Fantasy VII. Set in the dystopian cyberpunk metropolis of Midgar, players control the mercenary Cloud Strife. He joins AVALANCHE, an eco-terrorist group trying to stop the powerful megacorporation Shinra from using the planet's life essence as an energy source. The gameplay combines real-time action with role-playing elements. Remake was released for the PlayStation 4 in April 2020.",
      },
      {
        id: 202,
        cat:'JRPG',
        name: 'Crisis Core Reunion Final Fantasy VII Remake',
        videoid:'FkGYDD-CE9s',
        imgUrl:'/images/JRPG/Crisis Core Reunion Final Fantasy VII Remake.jpg',
        dec:"The story begins seven years before the events of FINAL FANTASY VII and follows Zack Fair, a young and ambitious Shinra SOLDIER operative. Zack is tasked with tracking down a missing SOLDIER 1st Class operative named Genesis Rhapsodos. But as his adventure unfolds, he discovers the dark secrets of Shinra’s experiments and the monsters they create. The game features a number of characters from the FINAL FANTASY VII franchise such as Cloud, Sephiroth, Aerith and others.",
      },
      {
        id: 203,
        cat:'JRPG',
        name: 'Final Fantasy X Remaster',
        videoid:'xv4uSttPFGI',
        imgUrl:'/images/JRPG/Final Fantasy X Remaster.jpg',
        dec:"Final Fantasy X/X-2 HD Remaster[a] is a high-definition remaster of the role-playing video games Final Fantasy X and Final Fantasy X-2, originally developed by Square (now Square Enix) on the PlayStation 2 in the early 2000s. It also features story content previously only found in the International versions, and a new audio drama set a year after the events of X-2. The collection saw graphical and musical revisions and is based on the international versions of both games, making certain content accessible to players outside of Japan for the first time.",
      },
      {
        id: 204,
        cat:'JRPG',
        name: 'Final Fantasy XII The Zodiac Age',
        videoid:'2IYu8ca8lus',
        imgUrl:'/images/JRPG/Final Fantasy XII The Zodiac Age.jpg',
        dec:"Final Fantasy XII[a] is a role-playing video game developed and published by Square Enix. The twelfth main installment of the Final Fantasy series, it was first released for the PlayStation 2 in 2006. It introduced several innovations to the series: an open world; a seamless battle system; a controllable camera; a customizable gambit system, which lets the player control the artificial intelligence (AI) of characters in battle; a license system, which determines what abilities and equipment can be used by characters; and hunting side quests, which allows the player to find and defeat increasingly difficult monsters in the game's open world. Final Fantasy XII also includes elements from previous games in the series, such as Chocobos and Moogles",
      },
      {
        id: 205,
        cat:'JRPG',
        name: 'Persona 5 Royal',
        videoid:'o9QjlLdYK5I',
        imgUrl:'/images/JRPG/Persona 5 Royal.jpg',
        dec:"Persona 5 is a 2016 role-playing video game developed by P-Studio and published by Atlus. It is the sixth installment in the Persona series, itself a part of the larger Megami Tensei franchise. It was released for the PlayStation 3 and PlayStation 4 game consoles in Japan in September 2016, and worldwide in April 2017. It was published by Atlus in Japan and North America, and by Deep Silver in PAL territories. An enhanced version featuring new content, Persona 5 Royal,[b] was released for the PlayStation 4 in Japan in October 2019, and worldwide in March 2020. It was published by Atlus in Japan and worldwide by its parent company Sega. Persona 5 Royal was later released for the Nintendo Switch, PlayStation 5, Windows, Xbox One, and Xbox Series X/S game consoles in October 2022.",
      },
      {
        id: 206,
        cat:'JRPG',
        name: 'Dragon Quest XI',
        videoid:'bg0oBJ9cXYM',
        imgUrl:'/images/JRPG/Dragon Quest XI.jpg',
        dec:"Dragon Quest XI: Echoes of an Elusive Age[c] is a role-playing video game by Square Enix. The eleventh entry in the long-running Dragon Quest video game series, it was released in Japan for the Nintendo 3DS and PlayStation 4 in July 2017 and worldwide for the PlayStation 4 and Windows in September 2018. An enhanced version, Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition,[d] was released for Nintendo Switch by Nintendo in September 2019; for PlayStation 4, Windows, and Xbox One in December 2020; and for Stadia in March 2021.",
      },
      {
        id: 207,
        cat:'JRPG',
        name: 'Nier Automata',
        videoid:'wJxNhJ8fjFk',
        imgUrl:'/images/JRPG/Nier Automata.jpg',
        dec:"Nier: Automata is a 2017 action role-playing game developed by PlatinumGames and published by Square Enix. It is a sequel to Nier (2010), itself a spin-off of and sequel to the Drakengard series. Nier: Automata was originally released for the PlayStation 4 and Windows via Steam, and an Xbox One port was published the following year. A Nintendo Switch port was released in 2022.",
      },
      {
        id: 208,
        cat:'JRPG',
        name: 'Nier Replicant',
        videoid:'gjjJbd-pa8g',
        imgUrl:'/images/JRPG/Nier Replicant.jpg',
        dec:"Nier is an action role-playing video game developed by Cavia and published by Square Enix for the PlayStation 3 and Xbox 360 in April 2010. In Japan, the game was released as Nier Replicant for the PlayStation 3 with a younger main character, while an alternative version titled Nier Gestalt with an older main character was released for the Xbox 360; Gestalt was released outside of Japan as Nier for both platforms. A remaster of the PlayStation 3 version of the game, Nier Replicant ver.1.22474487139... was released worldwide for PlayStation 4, Xbox One, and Windows on April 23, 2021.",
      },
      {
        id: 209,
        cat:'JRPG',
        name: 'Yakuza Like a Dragon',
        videoid:'hkygiqC7ulQ',
        imgUrl:'/images/JRPG/Yakuza Like a Dragon.jpg',
        dec:"Yakuza: Like a Dragon is a role-playing video game developed by Ryu Ga Gotoku Studio and published by Sega. The first mainline title in the Yakuza franchise developed as a turn-based RPG, it was released in Japan and Asia for PlayStation 4 on January 16, 2020. The western release of the game for PlayStation 4, Windows, Xbox One, and Xbox Series X/S on November 10, 2020 included new costumes, the English audio track and some previously paid DLC. This version was then released in Asia under the subtitle International[b] on February 25, 2021 for Windows and Xbox platforms. The game was released worldwide for PlayStation 5 on March 2, 2021, and a version for Amazon Luna launched on December 10, 2021.",
      },
      {
        id: 210,
        cat:'JRPG',
        name: 'Final Fantasy XV',
        videoid:'CNM6o9um1dc',
        imgUrl:'/images/JRPG/Final Fantasy XV.jpg',
        dec:"Final Fantasy XV is an action role-playing game developed and published by Square Enix. The fifteenth main installment of the Final Fantasy series, it was released for the PlayStation 4 and Xbox One in 2016, Windows in 2018, and as a launch title for Stadia in 2019. The game features an open world environment and action-based battle system, incorporating quick-switching weapons, elemental magic, and other features such as vehicle travel and camping. The base campaign was later expanded with downloadable content (DLC), adding further gameplay options such as additional playable characters and multiplayer.",
      },
      {
        id: 211,
        cat:'JRPG',
        name: 'Persona 5 Strikers',
        videoid:'KH0-THtNjTE',
        imgUrl:'/images/JRPG/Persona 5 Strikers.jpg',
        dec:"Persona 5 Strikers is an action role-playing game developed by Omega Force and P-Studio and published by Atlus. The game is a crossover between Koei Tecmo's Dynasty Warriors franchise and the Persona series developed by Atlus. The game's narrative is set half a year after the events of Persona 5, and follows Joker and the rest of the Phantom Thieves of Hearts as they investigate a series of mysterious events involving people across Japan.",
      },


]